-- Converted from db/ssm98yok.sql for the public demo deployment.

CREATE SCHEMA IF NOT EXISTS ot_ssm98yok;
SET search_path TO ot_ssm98yok;

CREATE TABLE IF NOT EXISTS address (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  addtime timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  userid bigint NOT NULL,
  address varchar(200) NOT NULL,
  name varchar(200) NOT NULL,
  phone varchar(200) NOT NULL,
  isdefault varchar(200) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS caipinfenlei (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  addtime timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  caipinfenlei varchar(200) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT caipinfenlei_caipinfenlei_key UNIQUE (caipinfenlei)
);

CREATE TABLE IF NOT EXISTS caipinxinxi (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  addtime timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  caipinmingcheng varchar(200) NOT NULL,
  caipinfenlei varchar(200) NOT NULL,
  tupian varchar(200) DEFAULT NULL,
  cailiao varchar(200) DEFAULT NULL,
  fenliang varchar(200) DEFAULT NULL,
  caipinjieshao text,
  cantingmingcheng varchar(200) DEFAULT NULL,
  lianxidianhua varchar(200) DEFAULT NULL,
  clicktime timestamp DEFAULT NULL,
  clicknum integer DEFAULT 0,
  price double precision NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS cantingxinxi (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  addtime timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  cantingmingcheng varchar(200) NOT NULL,
  cantingleixing varchar(200) NOT NULL,
  cantingtupian varchar(200) DEFAULT NULL,
  peisongshijian varchar(200) DEFAULT NULL,
  peisongfuwu varchar(200) DEFAULT NULL,
  lianxidianhua varchar(200) DEFAULT NULL,
  cantingdizhi varchar(200) DEFAULT NULL,
  cantingjieshao text,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS cart (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  addtime timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  tablename varchar(200) DEFAULT 'caipinxinxi',
  userid bigint NOT NULL,
  goodid bigint NOT NULL,
  goodname varchar(200) DEFAULT NULL,
  picture varchar(200) DEFAULT NULL,
  buynumber integer NOT NULL,
  price double precision DEFAULT NULL,
  discountprice double precision DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS chat (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  addtime timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  userid bigint NOT NULL,
  adminid bigint DEFAULT NULL,
  ask text,
  reply text,
  isreply integer DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS config (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name varchar(100) NOT NULL,
  value varchar(100) DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS dingdanpingjia (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  addtime timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  dingdanbianhao varchar(200) NOT NULL,
  caipinmingcheng varchar(200) NOT NULL,
  caipinfenlei varchar(200) DEFAULT NULL,
  pingfen varchar(200) DEFAULT NULL,
  pingjianeirong text,
  pingjiariqi date DEFAULT NULL,
  yonghuming varchar(200) DEFAULT NULL,
  shouji varchar(200) DEFAULT NULL,
  sfsh varchar(200) DEFAULT '否',
  shhf text,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS discusscaipinxinxi (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  addtime timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  refid bigint NOT NULL,
  userid bigint NOT NULL,
  content text NOT NULL,
  reply text,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS discusscantingxinxi (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  addtime timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  refid bigint NOT NULL,
  userid bigint NOT NULL,
  content text NOT NULL,
  reply text,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS news (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  addtime timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title varchar(200) NOT NULL,
  introduction text,
  picture varchar(200) NOT NULL,
  content text NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  addtime timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  orderid varchar(200) NOT NULL,
  tablename varchar(200) DEFAULT 'caipinxinxi',
  userid bigint NOT NULL,
  goodid bigint NOT NULL,
  goodname varchar(200) DEFAULT NULL,
  picture varchar(200) DEFAULT NULL,
  buynumber integer NOT NULL,
  price double precision NOT NULL DEFAULT 0,
  discountprice double precision DEFAULT 0,
  total double precision NOT NULL DEFAULT 0,
  discounttotal double precision DEFAULT 0,
  type integer DEFAULT 1,
  status varchar(200) DEFAULT NULL,
  address varchar(200) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT orders_orderid_key UNIQUE (orderid)
);

CREATE TABLE IF NOT EXISTS storeup (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  addtime timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  userid bigint NOT NULL,
  refid bigint DEFAULT NULL,
  tablename varchar(200) DEFAULT NULL,
  name varchar(200) NOT NULL,
  picture varchar(200) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS token (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  userid bigint NOT NULL,
  username varchar(100) NOT NULL,
  tablename varchar(100) DEFAULT NULL,
  role varchar(100) DEFAULT NULL,
  token varchar(200) NOT NULL,
  addtime timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expiratedtime timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS users (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  username varchar(100) NOT NULL,
  password varchar(100) NOT NULL,
  role varchar(100) DEFAULT '管理员',
  addtime timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS yonghu (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  addtime timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  yonghuming varchar(200) NOT NULL,
  mima varchar(200) NOT NULL,
  xingming varchar(200) NOT NULL,
  xingbie varchar(200) DEFAULT NULL,
  touxiang varchar(200) DEFAULT NULL,
  shouji varchar(200) DEFAULT NULL,
  money double precision DEFAULT 0,
  PRIMARY KEY (id),
  CONSTRAINT yonghu_yonghuming_key UNIQUE (yonghuming)
);

INSERT INTO address VALUES (1,'2021-01-25 02:23:59',1,'宇宙银河系金星1号','金某','13823888881','是'),(2,'2021-01-25 02:23:59',2,'宇宙银河系木星1号','木某','13823888882','是'),(3,'2021-01-25 02:23:59',3,'宇宙银河系水星1号','水某','13823888883','是'),(4,'2021-01-25 02:23:59',4,'宇宙银河系火星1号','火某','13823888884','是'),(5,'2021-01-25 02:23:59',5,'宇宙银河系土星1号','土某','13823888885','是'),(6,'2021-01-25 02:23:59',6,'宇宙银河系月球1号','月某','13823888886','是')
ON CONFLICT (id) DO NOTHING;

INSERT INTO caipinfenlei VALUES (31,'2021-01-25 02:23:59','菜品分类1'),(32,'2021-01-25 02:23:59','菜品分类2'),(33,'2021-01-25 02:23:59','菜品分类3'),(34,'2021-01-25 02:23:59','菜品分类4'),(35,'2021-01-25 02:23:59','菜品分类5'),(36,'2021-01-25 02:23:59','菜品分类6')
ON CONFLICT (id) DO NOTHING;

INSERT INTO caipinxinxi VALUES (41,'2021-01-25 02:23:59','菜品名称1','菜品分类1','https://ot-ssm98yok-api-273280-7-1369167244.sh.run.tcloudbase.com/ssm98yok/upload/caipinxinxi_tupian1.jpg','材料1','份量1','菜品介绍1','餐厅名称1','联系电话1','2021-01-25 10:23:59',1,99.9),(42,'2021-01-25 02:23:59','菜品名称2','菜品分类2','https://ot-ssm98yok-api-273280-7-1369167244.sh.run.tcloudbase.com/ssm98yok/upload/caipinxinxi_tupian2.jpg','材料2','份量2','菜品介绍2','餐厅名称2','联系电话2','2021-01-25 10:23:59',2,99.9),(43,'2021-01-25 02:23:59','菜品名称3','菜品分类3','https://ot-ssm98yok-api-273280-7-1369167244.sh.run.tcloudbase.com/ssm98yok/upload/caipinxinxi_tupian3.jpg','材料3','份量3','菜品介绍3','餐厅名称3','联系电话3','2021-01-25 10:23:59',3,99.9),(44,'2021-01-25 02:23:59','菜品名称4','菜品分类4','https://ot-ssm98yok-api-273280-7-1369167244.sh.run.tcloudbase.com/ssm98yok/upload/caipinxinxi_tupian4.jpg','材料4','份量4','菜品介绍4','餐厅名称4','联系电话4','2021-01-25 10:23:59',4,99.9),(45,'2021-01-25 02:23:59','菜品名称5','菜品分类5','https://ot-ssm98yok-api-273280-7-1369167244.sh.run.tcloudbase.com/ssm98yok/upload/caipinxinxi_tupian5.jpg','材料5','份量5','菜品介绍5','餐厅名称5','联系电话5','2021-01-25 10:23:59',5,99.9),(46,'2021-01-25 02:23:59','菜品名称6','菜品分类6','https://ot-ssm98yok-api-273280-7-1369167244.sh.run.tcloudbase.com/ssm98yok/upload/caipinxinxi_tupian6.jpg','材料6','份量6','菜品介绍6','餐厅名称6','联系电话6','2021-01-25 10:23:59',6,99.9)
ON CONFLICT (id) DO NOTHING;

INSERT INTO cantingxinxi VALUES (21,'2021-01-25 02:23:59','餐厅名称1','餐厅类型1','https://ot-ssm98yok-api-273280-7-1369167244.sh.run.tcloudbase.com/ssm98yok/upload/cantingxinxi_cantingtupian1.jpg','配送时间1','配送服务1','联系电话1','餐厅地址1','餐厅介绍1'),(22,'2021-01-25 02:23:59','餐厅名称2','餐厅类型2','https://ot-ssm98yok-api-273280-7-1369167244.sh.run.tcloudbase.com/ssm98yok/upload/cantingxinxi_cantingtupian2.jpg','配送时间2','配送服务2','联系电话2','餐厅地址2','餐厅介绍2'),(23,'2021-01-25 02:23:59','餐厅名称3','餐厅类型3','https://ot-ssm98yok-api-273280-7-1369167244.sh.run.tcloudbase.com/ssm98yok/upload/cantingxinxi_cantingtupian3.jpg','配送时间3','配送服务3','联系电话3','餐厅地址3','餐厅介绍3'),(24,'2021-01-25 02:23:59','餐厅名称4','餐厅类型4','https://ot-ssm98yok-api-273280-7-1369167244.sh.run.tcloudbase.com/ssm98yok/upload/cantingxinxi_cantingtupian4.jpg','配送时间4','配送服务4','联系电话4','餐厅地址4','餐厅介绍4'),(25,'2021-01-25 02:23:59','餐厅名称5','餐厅类型5','https://ot-ssm98yok-api-273280-7-1369167244.sh.run.tcloudbase.com/ssm98yok/upload/cantingxinxi_cantingtupian5.jpg','配送时间5','配送服务5','联系电话5','餐厅地址5','餐厅介绍5'),(26,'2021-01-25 02:23:59','餐厅名称6','餐厅类型6','https://ot-ssm98yok-api-273280-7-1369167244.sh.run.tcloudbase.com/ssm98yok/upload/cantingxinxi_cantingtupian6.jpg','配送时间6','配送服务6','联系电话6','餐厅地址6','餐厅介绍6')
ON CONFLICT (id) DO NOTHING;

INSERT INTO chat VALUES (61,'2021-01-25 02:23:59',1,1,'提问1','回复1',1),(62,'2021-01-25 02:23:59',2,2,'提问2','回复2',2),(63,'2021-01-25 02:23:59',3,3,'提问3','回复3',3),(64,'2021-01-25 02:23:59',4,4,'提问4','回复4',4),(65,'2021-01-25 02:23:59',5,5,'提问5','回复5',5),(66,'2021-01-25 02:23:59',6,6,'提问6','回复6',6)
ON CONFLICT (id) DO NOTHING;

INSERT INTO config VALUES (1,'picture1','https://ot-ssm98yok-api-273280-7-1369167244.sh.run.tcloudbase.com/ssm98yok/upload/picture1.jpg'),(2,'picture2','https://ot-ssm98yok-api-273280-7-1369167244.sh.run.tcloudbase.com/ssm98yok/upload/picture2.jpg'),(3,'picture3','https://ot-ssm98yok-api-273280-7-1369167244.sh.run.tcloudbase.com/ssm98yok/upload/picture3.jpg'),(6,'homepage',NULL)
ON CONFLICT (id) DO NOTHING;

INSERT INTO dingdanpingjia VALUES (51,'2021-01-25 02:23:59','订单编号1','菜品名称1','菜品分类1','1','评价内容1','2021-01-25','用户名1','手机1','是',''),(52,'2021-01-25 02:23:59','订单编号2','菜品名称2','菜品分类2','1','评价内容2','2021-01-25','用户名2','手机2','是',''),(53,'2021-01-25 02:23:59','订单编号3','菜品名称3','菜品分类3','1','评价内容3','2021-01-25','用户名3','手机3','是',''),(54,'2021-01-25 02:23:59','订单编号4','菜品名称4','菜品分类4','1','评价内容4','2021-01-25','用户名4','手机4','是',''),(55,'2021-01-25 02:23:59','订单编号5','菜品名称5','菜品分类5','1','评价内容5','2021-01-25','用户名5','手机5','是',''),(56,'2021-01-25 02:23:59','订单编号6','菜品名称6','菜品分类6','1','评价内容6','2021-01-25','用户名6','手机6','是','')
ON CONFLICT (id) DO NOTHING;

INSERT INTO discusscaipinxinxi VALUES (131,'2021-01-25 02:23:59',1,1,'评论内容1','回复内容1'),(132,'2021-01-25 02:23:59',2,2,'评论内容2','回复内容2'),(133,'2021-01-25 02:23:59',3,3,'评论内容3','回复内容3'),(134,'2021-01-25 02:23:59',4,4,'评论内容4','回复内容4'),(135,'2021-01-25 02:23:59',5,5,'评论内容5','回复内容5'),(136,'2021-01-25 02:23:59',6,6,'评论内容6','回复内容6')
ON CONFLICT (id) DO NOTHING;

INSERT INTO discusscantingxinxi VALUES (121,'2021-01-25 02:23:59',1,1,'评论内容1','回复内容1'),(122,'2021-01-25 02:23:59',2,2,'评论内容2','回复内容2'),(123,'2021-01-25 02:23:59',3,3,'评论内容3','回复内容3'),(124,'2021-01-25 02:23:59',4,4,'评论内容4','回复内容4'),(125,'2021-01-25 02:23:59',5,5,'评论内容5','回复内容5'),(126,'2021-01-25 02:23:59',6,6,'评论内容6','回复内容6')
ON CONFLICT (id) DO NOTHING;

INSERT INTO news VALUES (111,'2021-01-25 02:23:59','标题1','简介1','https://ot-ssm98yok-api-273280-7-1369167244.sh.run.tcloudbase.com/ssm98yok/upload/news_picture1.jpg','内容1'),(112,'2021-01-25 02:23:59','标题2','简介2','https://ot-ssm98yok-api-273280-7-1369167244.sh.run.tcloudbase.com/ssm98yok/upload/news_picture2.jpg','内容2'),(113,'2021-01-25 02:23:59','标题3','简介3','https://ot-ssm98yok-api-273280-7-1369167244.sh.run.tcloudbase.com/ssm98yok/upload/news_picture3.jpg','内容3'),(114,'2021-01-25 02:23:59','标题4','简介4','https://ot-ssm98yok-api-273280-7-1369167244.sh.run.tcloudbase.com/ssm98yok/upload/news_picture4.jpg','内容4'),(115,'2021-01-25 02:23:59','标题5','简介5','https://ot-ssm98yok-api-273280-7-1369167244.sh.run.tcloudbase.com/ssm98yok/upload/news_picture5.jpg','内容5'),(116,'2021-01-25 02:23:59','标题6','简介6','https://ot-ssm98yok-api-273280-7-1369167244.sh.run.tcloudbase.com/ssm98yok/upload/news_picture6.jpg','内容6')
ON CONFLICT (id) DO NOTHING;

INSERT INTO users VALUES (1,'abo','abo','管理员','2021-01-25 02:23:59')
ON CONFLICT (id) DO NOTHING;

INSERT INTO yonghu VALUES (11,'2021-01-25 02:23:59','用户1','123456','姓名1','男','https://ot-ssm98yok-api-273280-7-1369167244.sh.run.tcloudbase.com/ssm98yok/upload/yonghu_touxiang1.jpg','13823888881',100),(12,'2021-01-25 02:23:59','用户2','123456','姓名2','男','https://ot-ssm98yok-api-273280-7-1369167244.sh.run.tcloudbase.com/ssm98yok/upload/yonghu_touxiang2.jpg','13823888882',100),(13,'2021-01-25 02:23:59','用户3','123456','姓名3','男','https://ot-ssm98yok-api-273280-7-1369167244.sh.run.tcloudbase.com/ssm98yok/upload/yonghu_touxiang3.jpg','13823888883',100),(14,'2021-01-25 02:23:59','用户4','123456','姓名4','男','https://ot-ssm98yok-api-273280-7-1369167244.sh.run.tcloudbase.com/ssm98yok/upload/yonghu_touxiang4.jpg','13823888884',100),(15,'2021-01-25 02:23:59','用户5','123456','姓名5','男','https://ot-ssm98yok-api-273280-7-1369167244.sh.run.tcloudbase.com/ssm98yok/upload/yonghu_touxiang5.jpg','13823888885',100),(16,'2021-01-25 02:23:59','用户6','123456','姓名6','男','https://ot-ssm98yok-api-273280-7-1369167244.sh.run.tcloudbase.com/ssm98yok/upload/yonghu_touxiang6.jpg','13823888886',100)
ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('ot_ssm98yok.address', 'id'), COALESCE((SELECT MAX(id) FROM address), 1));
SELECT setval(pg_get_serial_sequence('ot_ssm98yok.caipinfenlei', 'id'), COALESCE((SELECT MAX(id) FROM caipinfenlei), 1));
SELECT setval(pg_get_serial_sequence('ot_ssm98yok.caipinxinxi', 'id'), COALESCE((SELECT MAX(id) FROM caipinxinxi), 1));
SELECT setval(pg_get_serial_sequence('ot_ssm98yok.cantingxinxi', 'id'), COALESCE((SELECT MAX(id) FROM cantingxinxi), 1));
SELECT setval(pg_get_serial_sequence('ot_ssm98yok.cart', 'id'), COALESCE((SELECT MAX(id) FROM cart), 1));
SELECT setval(pg_get_serial_sequence('ot_ssm98yok.chat', 'id'), COALESCE((SELECT MAX(id) FROM chat), 1));
SELECT setval(pg_get_serial_sequence('ot_ssm98yok.config', 'id'), COALESCE((SELECT MAX(id) FROM config), 1));
SELECT setval(pg_get_serial_sequence('ot_ssm98yok.dingdanpingjia', 'id'), COALESCE((SELECT MAX(id) FROM dingdanpingjia), 1));
SELECT setval(pg_get_serial_sequence('ot_ssm98yok.discusscaipinxinxi', 'id'), COALESCE((SELECT MAX(id) FROM discusscaipinxinxi), 1));
SELECT setval(pg_get_serial_sequence('ot_ssm98yok.discusscantingxinxi', 'id'), COALESCE((SELECT MAX(id) FROM discusscantingxinxi), 1));
SELECT setval(pg_get_serial_sequence('ot_ssm98yok.news', 'id'), COALESCE((SELECT MAX(id) FROM news), 1));
SELECT setval(pg_get_serial_sequence('ot_ssm98yok.orders', 'id'), COALESCE((SELECT MAX(id) FROM orders), 1));
SELECT setval(pg_get_serial_sequence('ot_ssm98yok.storeup', 'id'), COALESCE((SELECT MAX(id) FROM storeup), 1));
SELECT setval(pg_get_serial_sequence('ot_ssm98yok.token', 'id'), COALESCE((SELECT MAX(id) FROM token), 1));
SELECT setval(pg_get_serial_sequence('ot_ssm98yok.users', 'id'), COALESCE((SELECT MAX(id) FROM users), 1));
SELECT setval(pg_get_serial_sequence('ot_ssm98yok.yonghu', 'id'), COALESCE((SELECT MAX(id) FROM yonghu), 1));
